### PR TITLE
feat: adds wait option to multiple cmds #518

### PR DESCRIPTION
**Pull request by srinandan**

### CODE REVIEW

**Review by kurtkanaskie — CHANGES_REQUESTED** [review]
environments create --env=cli --deptype=PROXY --wait
OK

envgroups create --name=envgrp-cli --hosts=api.exco.com,api-test.exco.com --wait
OK

instances attachments detach --name=us-east1 --env=test
should have --wait also.

attach didn't wait
```
instances attachments attach --name=us-east1 --env=test --wait
{
	"name": "organizations/apigeex-mint-kurt/operations/256ac430-7632-42be-a6c7-d9ced21e3fc9",
	"metadata": {
		"@type": "type.googleapis.com/google.cloud.apigee.v1.OperationMetadata",
		"operationType": "INSERT",
		"targetResourceName": "organizations/apigeex-mint-kurt/instances/us-east1/attachments/9683d26c-be8e-4059-87fe-a3394b745dfc",
		"state": "IN_PROGRESS"
	}
}

Checking creation status in 10 seconds
Instance attachment completed with status:  ACTIVE
```

**Comment by kurtkanaskie** [comment]
Attaching an env to an instance waits but displays incorrect messages
```
gorun --org=$ORG instances attachments attach --name=us-east1 --env=test --wait
{
	"name": "organizations/apigeex-mint-kurt/operations/09f307e8-93fb-4e81-9b2b-e64e6cd12c2e",
	"metadata": {
		"@type": "type.googleapis.com/google.cloud.apigee.v1.OperationMetadata",
		"operationType": "INSERT",
		"targetResourceName": "organizations/apigeex-mint-kurt/instances/us-east1/attachments/93a3e83c-ea04-4106-a23c-4c2ff9bc77e2",
		"state": "IN_PROGRESS"
	}
}

Checking creation status in 10 seconds
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment status is: %!s(<nil>). Waiting 10 seconds.
Instance attachment completed
```

**Review by kurtkanaskie — CHANGES_REQUESTED** [review]
See previous note regarding status messages.

respMap["state"] doesn't exist, need something like $respBody.metadata.state

**Comment by kurtkanaskie** [comment]
`instances delete` and other APIs that return an LRO should include --wait

Error condition waits 10 seconds even on immediate result
```
gorun instances create --org=$ORG --location=us-east1 --name=us-east1 --wait
{
  "error": {
    "code": 409,
    "message": "instance \"organizations/apigeex-custom/instances/us-east1\" already exists",
    "status": "ALREADY_EXISTS",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "2905311160183436725"
      }
    ]
  }
}

Checking creation status in 10 seconds
Instance creation failed with status:  CREATING
```

**Comment by srinandan** [comment]
This addresses the bug when an instance already exists or otherwise fails. 

This PR doesn't contain `wait` for deletion.

**Review by kurtkanaskie — CHANGES_REQUESTED** [review]
Testing instance creation.
```
gorun instances create --org=$ORG --location=us-east1 --name=us-east1 --wait
{
	"name": "organizations/apigeex-custom/operations/5e307bd8-186b-452a-8531-b41edd599e57",
	"metadata": {
		"@type": "type.googleapis.com/google.cloud.apigee.v1.OperationMetadata",
		"operationType": "INSERT",
		"targetResourceName": "organizations/apigeex-custom/instances/us-east1",
		"state": "IN_PROGRESS"
	}
}

Checking creation status in 10 seconds
Instance creation failed with status:  CREATING
```

```
gorun operations list --org=$ORG --state=IN_PROGRESS --complete-state=Both
{
	"operations": [
		{
			"name": "organizations/apigeex-custom/operations/5e307bd8-186b-452a-8531-b41edd599e57",
			"metadata": {
				"@type": "type.googleapis.com/google.cloud.apigee.v1.OperationMetadata",
				"operationType": "INSERT",
				"targetResourceName": "organizations/apigeex-custom/instances/us-east1",
				"state": "IN_PROGRESS",
				"progress": {
					"description": "Allocating IP ranges to Apigee \"us-east1\" instance for VPC Peering",
					"percentDone": 1
				}
			},
			"error": {}
		}
	]
}
```

**Comment by kurtkanaskie** [comment]
LGTM

**Review by kurtkanaskie — APPROVED** [review]
LGTM

**Pull request merged**
