### PR TITLE
Add cobra completion command

### PR DESCRIPTION
**Pull request by yuriylesyuk**

### CODE REVIEW

**Comment by ssvaidyanathan** [comment]
@yuriylesyuk - can you please add the copyright/license section to the files

**Comment by yuriylesyuk** [comment]
Added a copyright fragment to the source file;
The license for cobra library is already included in the 3rd-party licences file.

**Comment by srinandan** [comment]
Autocompletion is already there

```
apigeecli completion

Generate the autocompletion script for apigeecli for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  apigeecli completion [command]

Available Commands:
  bash        generate the autocompletion script for bash
  fish        generate the autocompletion script for fish
  powershell  generate the autocompletion script for powershell
  zsh         generate the autocompletion script for zsh
```

**Comment by srinandan** [comment]
Please reopen the PR if what we already doesn't work (or doesn't work well)

**Pull request closed without merging**
