### PR TITLE
Added linux install script + instructions

### PR DESCRIPTION
**Pull request by tyayers**
Added an easy install script for Linux, maybe useful for others to easily deploy the CLI to their Linux environments.

### CODE REVIEW

**Comment by srinandan** [comment]
I have two questions
1) we can make this more generic to include Darwin also
2) Should we automatically move the file to `/use/bin`? seems like that can be a question for the user.

**Comment by srinandan** [comment]
Can you please take a look at: https://github.com/apigee/apigeecli/pull/11

**Comment by tyayers** [comment]
Hi, tested the download branch solution, at least on Debian it does download to a local dir, but doesn't ask to put the binary in a PATH location.. Agree that /usr/bin is not the best solution, how about $HOME/.local/bin?  At least on Debian this works well, and is a great place since it's in the PATH and then the CLI is immediately usable for the local user..  Would that work on Darwin (I'm not a mac user so can't test..)

My requirement would be that with one command the CLI is installed and usable for automation jobs, so no user interaction required (so in Gitlab build runners, etc..).

**Comment by srinandan** [comment]
I reworked it a bit. I have followed the same principle as istioctl (https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCtl.sh). I will close this PR, we can discuss on the other PR.

You can still run it with a single command like so:

```
curl -L https://raw.githubusercontent.com/apigee/apigeecli/master/downloadLatest.sh | sh - && export PATH=$PATH:$HOME/.apigeecli/bin
```

**Pull request closed without merging**
