### PR TITLE
feat: allow delete by app name only #338

### PR DESCRIPTION
**Pull request by srinandan**

### CODE REVIEW

**Review by kurtkanaskie — CHANGES_REQUESTED** [review]
App names are not unique across developers, so this will delete the first app that matches the name. We shouldn't do this, unless I'm missing the use case.

**Comment by srinandan** [comment]
Yeah, point taken. I will remove this feature, but keep some of the other flags in the PR

**Comment by srinandan** [comment]
I have reversed the option that deletes by name.

**Comment by srinandan** [comment]
`--name` return all apps that match the name. Not just the first match.

**Review by kurtkanaskie — APPROVED** [review]
LGTM

**Pull request merged**
