### PR TITLE
fix: kvm import logic (#223)

### PR DESCRIPTION
**Pull request by g-greatdevaks**
Fixes issue #223.

### CODE REVIEW

**Comment by srinandan** [comment]
I think we should add a flag to control whether such an import should fail or not. WDYT?

**Comment by g-greatdevaks** [comment]
@srinandan That's a good idea. It would leave room for incorporating changes in future with respect to the Apigee APIs for KVMs.

I will introduce a flag to skip the import for existing KVMs.

**Comment by g-greatdevaks** [comment]
I have introduced a flag for skipping the import of existing KVMs and also updated the `org import` logic with the same.
I didn't touch the documentation as I see that a GitHub Actions workflow for updating the documentation already exists.

@kurtkanaskie Kindly review once.

**Comment by kurtkanaskie** [comment]
Firstly I think the option should follow existing naming conventions and use lowerCamelCase and show the default value. 
e.g.  --importKVMs   Import KVMs and entries; default false
For example the output from import help is:
```
Usage:
  apigeecli organizations import [flags]

Flags:
  -c, --conn int             Number of connections (default 4)
  -f, --folder string        folder containing API proxy bundles
  -h, --help                 help for import
      --importDebugmask      Import debugmask configuration; default false
      --importTrace          Import distributed trace configuration; default false
  -o, --org string           Apigee organization name
      --skip-existing-kvms   Skip import of existing KVM(s)

Global Flags:
  -a, --account string   Path Service Account private key in JSON
      --disable-check    Disable check for newer versions
      --no-output        Disable printing all statements to stdout
      --print-output     Control printing of info log statements (default true)
  -t, --token string     Google OAuth Token
```

Secondly, I'm not able to get this to work, at all. I've exported an existing org `apigeex-payg-kurt` which has org level KVMs and an env KVM for `dev`. I copied `apigeex-payg-kurt_kvms.json` to `apigeex-payg-2023-03-23_kvms.json`. The resulting files after pruning is:
```.
├── apigeex-payg-2023-03-23_kvms.json
├── apigeex-payg-kurt_kvms.json
├── dev_kvms.json
├── env_dev_github-webhook_kvmfile_0.json
├── org_error-handling-v1_kvmfile_0.json
├── org_test-org-level_kvmfile_0.json
```

I ran 
```
go run ../main.go  organizations import --org=apigeex-payg-2023-03-23 --folder=. --conn=1 --token=$TOKEN 
Importing API Proxies...
Importing Sharedflows...
Check for files with KVM Entries
Map name github-webhook, path env_dev_github-webhook_kvmfile_0.json
Map name error-handling-v1, path org_error-handling-v1_kvmfile_0.json
Map name test-org-level, path org_test-org-level_kvmfile_0.json
Importing configuration for environment dev
Importing configuration for environment test-env
```

But no KVMs get created. What am I missing?

**Comment by kurtkanaskie** [comment]
Ah, now I see what I needed to do. After export I needed to rename files:
```
cp apigeex-payg-kurt_kvms.json org_apigeex-payg-kurt_kvms.json
cp dev_kvms.json env_dev_kvms.json
```
Given that, can we fix the export to add the `org_` and `env_` prefixes?

**Comment by g-greatdevaks** [comment]
@kurtkanaskie 
- Fixed the case for the flag and added description for the default value associated with the flag.
- For point 2 I think the JSON files that you mentioned are containing the list of KVMs and not the KVMEntries. The KVMEntries are already being exported with `org_` and `env_` prefixes, as shown [here](https://github.com/apigee/apigeecli/blob/3a65b974f46bd2dc07c0cae9d27c8d54e5445ef2/cmd/org/export.go#L295C2-L295C2).

**Comment by kurtkanaskie** [comment]
Testing the updates, I see some issues. After the export from org "apigeex-payg-kurt", I see these files:
```
tree .
.
├── apigeex-payg-kurt_kvms.json
├── dev_kvms.json
├── env_dev_github-webhook_kvmfile_0.json
├── org_error-handling-v1_kvmfile_0.json
├── org_test-org-level_kvmfile_0.json
├── proxies
│   ├── catch-all-v1.zip
│   └── notarget.zip
└── sharedflows
```
I have 2 org level KVMs "test-org-level" and "error-handling-v1"\
I have a single env level KVM "github-webhook" in "dev"

**Issue 1** - the output files containing the kvm names should follow the pattern: \
org_ORGNAME_kvms.json \
env_ENVNAME_kvms.json

To make the import work to org "apigeex-payg-2023-03-23"  I need to copy the exported files to follow that pattern. 
```
cp apigeex-payg-kurt_kvms.json org_apigeex-payg-2023-03-23_kvms.json
cp dev_kvms.json env_dev_kvms.json
```

**Issue 2**  - Import puts all KVMs in "dev" env.
After I correct the kvm names files, the import is placing all the KVMs into my dev environment.\
Using apigeecli, the import is correctly placing 2 KVMs in org and 1 KVM in env.

**Issue 3** - import says it's only importing names, but entries are created
```
Importing API Proxies...
Importing Sharedflows...
Check for files with KVM Entries
Map name github-webhook, path env_dev_github-webhook_kvmfile_0.json
Map name error-handling-v1, path org_error-handling-v1_kvmfile_0.json
Map name test-org-level, path org_test-org-level_kvmfile_0.json
Importing Org scoped KVMs...
Importing configuration for environment dev
	Importing KVM Names only...
```

**Issue 4** - skipExistingKVMs doesn't appear to work
Given I have 2 org level KVMs "test-org-level" and "error-handling-v1"\
And I have a single env level KVM "github-webhook"\
I deleted "error-handling-v1" so I could test that it gets created and others are skipped.
```
$ go run ../main.go kvms list --org apigeex-payg-2023-03-23 -t $TOKEN
[
	"test-org-level"
]

$ go run ../main.go kvms list --org apigeex-payg-2023-03-23 --env dev -t $TOKEN
[
	"github-webhook"
]

$ go run ../main.go organizations import --org apigeex-payg-2023-03-23 --folder=. --conn 1 --token $TOKEN --skipExistingKVMs=true
Importing API Proxies...
Importing Sharedflows...
Check for files with KVM Entries
Skipping Map name github-webhook having path env_dev_github-webhook_kvmfile_0.json as it already exists at the Apigee Environment level
Map name error-handling-v1, path org_error-handling-v1_kvmfile_0.json
Map name test-org-level, path org_test-org-level_kvmfile_0.json
Importing Org scoped KVMs...
Importing configuration for environment dev
	Importing KVM Names only...
{
  "error": {
    "code": 409,
    "message": "KeyValueMap github-webhook already exists",
    "status": "ABORTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "keyvaluemap.service.keyvaluemap_already_exist",
            "subject": "[2002:a17:531:3006::]:4389:bibuz12:9830:619912:26405482",
            "description": "KeyValueMap github-webhook already exists"
          }
        ]
      }
    ]
  }
}

Error: Conflict - request conflicts with the current state of the server
```

After that:
```
$ go run ../main.go kvms list --org apigeex-payg-2023-03-23 -t $TOKEN
[
	"test-org-level"
]

$ go run ../main.go kvms list --org apigeex-payg-2023-03-23 -t $TOKEN
[apigeex-payg-kurt:~/work/APIGEEX/apigeecli/apigeecli/test-kvm-import-new]$ go run ../main.go kvms list --org apigeex-payg-2023-03-23 --env dev -t $TOKEN
[
	"error-handling-v1",
	"github-webhook",
	"test-org-level"
]
```

**Comment by ssvaidyanathan** [comment]
@g-greatdevaks - am closing this issue for now. Please submit a new PR once you have the fix

**Pull request closed without merging**
